sonar.organization=nodero-group-project
sonar.projectKey=Nodero-Group-Project_ade-chat-assistant-frontend

sonar.sources=ade-chat-assistant-frontend/src
sonar.tests=ade-chat-assistant-frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/htmlcov/**,**/*.json

sonar.javascript.lcov.reportPaths=ade-chat-assistant-frontend/coverage/lcov.info